-- INSTITUTO NACIONAL DE APRENDIZAJE
-- PROGRAMADOR DE APLICACIONES
-- MÓDULO: GESTIÓN DE BASES DE DATOS
-- PROFESOR: LUIS CHACÓN ZUÑIGA
-- ESTUDIANTE: EDDY CAMPOS JIMÉNEZ
-- PROYECTO BASE DE DATOS MATRICULA
-- FECHA CREACIÓN: 5 FEB 2023
-- ULTIMA ACTUALIZACION: 5 FEB 2023
----------------------------------------------------------------------------------------
--USA LA BASE DE DATOS
USE EDDY_PROYECTOBD_FASE2
GO
-------------------------------------CONSULTAS------------------------------------------

--1. CONSULTAS DE SELECCION SIMPLE -----------------------------------------------------

--A. MOSTRAR EL ID, CARNET, NOMBRE, APELLIDO1, APELLIDO2 Y NUMCEDULA DE LOS ESTUDIANTES MATRICULADOS EN LA MATERIA 'A_PAWE_HT'
SELECT E.ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO_01, APELLIDO_02, NUM_CEDULA
	FROM ESTUDIANTES E INNER JOIN MATRICULAS M --LOS QUE ESTAN EN AMBAS TABLAS
	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE
	WHERE ID_MATERIA_ABIERTA = 'A_PAWE_HT'

--B. MOSTRAR TODOS LOS DETALLES DEL CERTIFICADO DEL PROFESOR ENCARGADO DE LA MATERIA 'A_DIMO_A1'
SELECT ID_CERTIFICADO, C.ID_PROFESOR, NOMBRE_CERTIFICADO, NUM_FOLIO, FECHA_EXPEDICION
	FROM CERTIFICACIONES C INNER JOIN PROFESORES P --LOS QUE ESTAN EN AMBAS TABLAS
	ON C.ID_PROFESOR = P.ID_PROFESOR

	INNER JOIN MATERIAS_DISPONIBLES MD
	ON P.ID_PROFESOR = MD.ID_PROFESOR

	WHERE ID_MATERIA_ABIERTA = 'A_DIMO_A1'

--C. MOSTRAR TODA LA INFORMACION SOLO DE LAS CARRERAS ABIERTAS
SELECT M.ID_MATERIA, ID_CARRERA, NOMBRE, HORAS, COSTO, REQUISITOS, DETALLES
	FROM MATERIAS M RIGHT JOIN MATERIAS_DISPONIBLES MD --LOS QUE ESTAN EN MATERIAS_DISPONIBLES (RIGHT)

	ON M.ID_MATERIA = MD.ID_MATERIA

SELECT * FROM MATERIAS
SELECT * FROM MATERIAS_DISPONIBLES

--D. MOSTRAR TODA LA INFORMACION SOLO DE LAS CARRERAS QUE TIENEN MATERIAS ABIERTAS Y CON CLASES SOLO EN LA TARDE
SELECT DISTINCT C.ID_CARRERA, C.NOMBRE, GRADO, DESCRIPCION, TOTAL_CREDITOS
	FROM CARRERAS C RIGHT JOIN MATERIAS M --LOS QUE ESTAN EN MATERIAS (RIGHT)
	ON C.ID_CARRERA = M.ID_CARRERA

	RIGHT JOIN MATERIAS_DISPONIBLES MD
	ON M.ID_MATERIA = MD.ID_MATERIA

	RIGHT JOIN GRUPOS G
	ON MD.ID_MATERIA_ABIERTA = G.ID_MATERIA_ABIERTA

	RIGHT JOIN HORARIOS H
	ON G.ID_GRUPO = H.ID_GRUPO
	WHERE HORAINICIO > '12:00'

SELECT * FROM MATERIAS
SELECT * FROM HORARIOS ORDER BY ID_GRUPO

--E. MUESTRA EL ID_EMPLEADO, NOMBRE, APELLIDOS (CONCATENADOS), NUM CEDULA Y CARNET DE LOS PROFESORES QUE NO DAN CLASES LOS LUNES NI VIERNES
SELECT DISTINCT E.ID_EMPLEADO,
				NOMBRE + ' '+ APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO, 
				NUM_CEDULA, CARNET
	FROM EMPLEADOS E RIGHT JOIN PROFESORES P --LOS QUE ESTAN EN PROFESORES (RIGHT)

	ON E.ID_EMPLEADO = P.ID_EMPLEADO
	RIGHT JOIN MATERIAS_DISPONIBLES MD

	ON P.ID_PROFESOR = MD.ID_PROFESOR
	RIGHT JOIN GRUPOS G

	ON MD.ID_MATERIA_ABIERTA = G.ID_MATERIA_ABIERTA
	RIGHT JOIN HORARIOS H

	ON G.ID_GRUPO = H.ID_GRUPO
	WHERE DIA <> 'L' AND DIA <> 'V'

--F. MUESTRA ID, NOMBRE Y APELLIDOS CONCATENADOS, PROVINCIA, CANTON, DISTRITO E ID MATERIA DE LOS ESTUDIANTES QUE EN LA FACTURA PAGAN MENOS DE 200 000
SELECT E.ID_ESTUDIANTE, CARNET, 
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   PROVINCIA, CANTON, DISTRITO, ID_MATERIA_ABIERTA
	FROM ESTUDIANTES E LEFT JOIN MATRICULAS M --LOS QUE ESTAN EN ESTUDIANTES (LEFT)

	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE
	LEFT JOIN FACTURAS F

	ON M.ID_COMPROBANTE = F.ID_COMPROBANTE
	WHERE MONTOTOTAL < 200000

SELECT * FROM FACTURAS

----------------------------------------------------------------------------------------

--2. CONSULTAS DE SELECCION UTILIZANDO FUNCIONES AGREGADAS -----------------------------

--A. MUESTRA ID, CARNET, NOMBRE Y APELLIDOS CONCATENADOS Y CUENTA DE LOS ESTUDIANTES QUE TIENE MATERIAS MATRICULAS Y LA CANTIDAD
SELECT E.ID_ESTUDIANTE, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   COUNT(ID_MATERIA_ABIERTA) AS CANTIDAD_MATERIAS --CUENTA LA CANTIDAD DE MATERIAS ABIERTAS
	FROM ESTUDIANTES E RIGHT JOIN MATRICULAS M --LOS QUE ESTAN EN MATRICULAS (RIGHT)
	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE

	RIGHT JOIN FACTURAS F
	ON M.ID_COMPROBANTE = F.ID_COMPROBANTE
	
	WHERE E.ID_ESTUDIANTE = M.ID_ESTUDIANTE
	GROUP BY E.ID_ESTUDIANTE, CARNET,  NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02

--B. MUESTRA ID, CARNET, NOMBRE COMPLETO CONCATENADO DE LOS PROFESORES ASIGNADOS Y LA CANTIDAD DE DIAS QUE IMPARTEN LECCIONES
SELECT E.ID_EMPLEADO, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   COUNT(DIA) AS CANTIDAD_DIAS --CUENTA LOS DIAS
	FROM EMPLEADOS E RIGHT JOIN PROFESORES P --LOS QUE ESTAN EN PROFESORES (RIGHT)
	ON E.ID_EMPLEADO = P.ID_EMPLEADO

	RIGHT JOIN MATERIAS_DISPONIBLES MD
	ON P.ID_PROFESOR = MD.ID_PROFESOR

	RIGHT JOIN GRUPOS G
	ON MD.ID_MATERIA_ABIERTA = G.ID_MATERIA_ABIERTA

	RIGHT JOIN HORARIOS H
	ON G.ID_GRUPO = H.ID_GRUPO

	GROUP BY  E.ID_EMPLEADO, CARNET, NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02

--C. MUESTRA ID, CARNET, NOMBRE COMPLETO Y SUMA DEL TOTAL DE CADA MATERIA MATRICULADA POR ESTUDIANTE
SELECT E.ID_ESTUDIANTE, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   SUM(MONTOTOTAL) AS TOTAL_POR_MATRICULAS --SUMA LOS MONTOS
	FROM ESTUDIANTES E RIGHT JOIN MATRICULAS M --LOS QUE ESTAN EN MATRICULAS (RIGHT)
	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE

	RIGHT JOIN FACTURAS F
	ON M.ID_COMPROBANTE = F.ID_COMPROBANTE
	
	GROUP BY  E.ID_ESTUDIANTE, CARNET,NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02

--D. MUESTRA ID, CARNET, NOMBRE COMPLETO Y PROMEDIO DE LAS NOTAS DE LOS ESTUDIANTES MATRICULADOS
SELECT E.ID_ESTUDIANTE, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   AVG(NOTAPONDERADA) AS PROMEDIO_NOTAS --CULCULA EL PROMEDIO DE LS NOTAS
	FROM ESTUDIANTES E INNER JOIN MATRICULAS M --LOS QUE ESTAN EN AMBAS TABLAS
	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE

	GROUP BY E.ID_ESTUDIANTE, CARNET, NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02

--SE ACTUALIZA UN VALOR PARA PRUEBA
UPDATE MATRICULAS
	SET NOTAPONDERADA = 92.2
	WHERE ID_COMPROBANTE = 'C4'

--E. MUESTRA LA CANTIDAD MAXIMA DE LAPTOPS EN LOS LABORATORIOS
SELECT MAX(CANTIDAD_LAPTOPS) AS MAXIMA_CANTIDAD_LAPTOPS --BUSCA LA CANTIDAD MAXIMA DE LAPTOPS
	FROM LABORATORIOS

--F. MUESTRA LA MATERIA QUE TIENE EL MENOR COSTO
SELECT MIN(COSTO) AS MATERIA_MENOR_COSTO --BUSCA EL COSTO MINIMO
	FROM MATERIAS

--G. MUESTRA ID_EMPLEADO, CARNET, NOMBRE COMPLETO, NUM CEDULA Y FECHA DE LOS PROFESORES CON CERTIFICADO CON FECHA DE EXPEDICION MAYOR AL AÑO 2015
SELECT E.ID_EMPLEADO, CARNET, 
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
	   NUM_CEDULA, 
	   CONVERT(varchar, FECHA_EXPEDICION, 103) AS FECHA_EXPEDICION --MUESTRA LA FECHA EN FORMATO '16/01/2021'
	FROM EMPLEADOS E INNER JOIN PROFESORES P --LOS QUE ESTAN EN AMBAS TABLAS
	ON E.ID_EMPLEADO = P.ID_EMPLEADO

	INNER JOIN CERTIFICACIONES C
	ON P.ID_PROFESOR = C.ID_PROFESOR

	WHERE DATEPART(YY, FECHA_EXPEDICION) > '2015' --SELECCIONA SOLO EL AÑO 

--H. MUESTRA EL ID, CARNTET, NOMBRE COMPLETO, NUMERO DE CEDULA, FECHA DE NACIMIENETO Y LA SUMA DE LOS CREDITOS DE LAS MATERIAS SOLO CUANDO ES MENOR A 10
SELECT E.ID_ESTUDIANTE, CARNET,
	    E.NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO,
		NUM_CEDULA, F_NACIMIENTO,
		SUM(CREDITOS) AS TOTAL_CREDITOS --SUMA LOS CREDITOS
	FROM ESTUDIANTES E INNER JOIN MATRICULAS M --LOS QUE ESTAN EN AMBAS TABLASE
	ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE

	INNER JOIN MATERIAS_DISPONIBLES MD
	ON M.ID_MATERIA_ABIERTA = MD.ID_MATERIA_ABIERTA

	INNER JOIN MATERIAS MA
	ON MD.ID_MATERIA = MA.ID_MATERIA

	GROUP BY E.ID_ESTUDIANTE, CARNET, E.NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02, NUM_CEDULA, F_NACIMIENTO
	HAVING SUM(CREDITOS) < 10 --MIENTRAS LA SUMA SEA MENOR A 10
	ORDER BY TOTAL_CREDITOS

SELECT * FROM MATERIAS

----------------------------------------------------------------------------------------

--3. CONSULTAS DE SELECION ORDENANDO DATOS ---------------------------------------------

--A. MUESTRA EL ID DE LA MATERIA, DE LA CARRERA EL NOMBRE, LAS HORAS Y SUMA LA CANTIDAD DE DIAS FERIADOS QUE SE APLICARAN SEGUN EL HORARIO
SELECT M.ID_MATERIA, ID_CARRERA, NOMBRE, HORAS,
	   COUNT(FECHA) AS CANTIDAD_FERIADOS --CUNTA LOS DIAS
	FROM MATERIAS M INNER JOIN MATERIAS_DISPONIBLES MD --LOS QUE ESTAN EN AMBAS TABLAS
	ON M.ID_MATERIA = MD.ID_MATERIA

	INNER JOIN GRUPOS G
	ON MD.ID_MATERIA_ABIERTA = G.ID_MATERIA_ABIERTA

	INNER JOIN HORARIOS H
	ON G.ID_GRUPO = H.ID_GRUPO

	INNER JOIN FERIADOS F
	ON H.ID_HORARIO = F.ID_HORARIO

	GROUP BY M.ID_MATERIA, ID_CARRERA, NOMBRE, HORAS
	ORDER BY ID_CARRERA

--B. MUESTRA EL ID DE LA MATERIA, DE LA CARRRERA, EL NOMBRE, LAS HORAS, EL COSTO, LOS CREDITOS
SELECT DISTINCT M.ID_MATERIA, ID_CARRERA, NOMBRE, HORAS, COSTO, CREDITOS,
	   MAX(CANTIDAD_LAPTOPS) AS LAB_MAYOR_CANT_LAPTOPS --BUSCA LA CANTIDAD MAXIMA DE LAPTOPS
	FROM MATERIAS M INNER JOIN MATERIAS_DISPONIBLES MD
	ON M.ID_MATERIA = MD.ID_MATERIA

	INNER JOIN GRUPOS G
	ON MD.ID_MATERIA_ABIERTA = G.ID_MATERIA_ABIERTA

	INNER JOIN LABORATORIOS L
	ON G.ID_LABORATORIO = L.ID_LABORATORIO

	GROUP BY M.ID_MATERIA, ID_CARRERA, NOMBRE, HORAS, COSTO, CREDITOS, REQUISITOS, DETALLES, ESTADO
	HAVING MAX(CANTIDAD_LAPTOPS) > 2 --MIENTRAS LA CANTIDAD SEA MAYOR A 2
	ORDER BY LAB_MAYOR_CANT_LAPTOPS DESC
	   	  
----------------------------------------------------------------------------------------

--4. CONSULTAS CON UNION O SUBCONSULTAS ------------------------------------------------

--A. MUESTRA ID GRUPO, ID MATERIA ABIERTA, Y EL CUPO MIENTRAS SEA MAYOR A 20 Y LA MAXIMA CANTIDAD DE SILLAS, MESAS Y LAPTOPS EN LOS LABORATORIOS
SELECT ID_GRUPO, ID_MATERIA_ABIERTA, ID_LABORATORIO, CUPO,
	   (SELECT MAX(CANTIDAD_LAPTOPS) --ESTA CONSULTA BUSCA LA CANTIDAD MAXIMA DE LAPTOPS
			FROM LABORATORIOS)AS MAX_LAPTOPS,
	   (SELECT MAX(CANTIDAD_SILLAS) --ESTA CONSULTA BUSCA LA CANTIDAD MAXIMA DE SILLAS
			FROM LABORATORIOS)AS MAX_SILLAS,
	   (SELECT MAX(CANTIDAD_ESCRITORIOS) --ESTA CONSULTA BUSCA LA CANTIDAD MAXIMA DE ESCRITORIOS
			FROM LABORATORIOS)AS MAX_ESCRITORIOS
	FROM GRUPOS
	WHERE CUPO > 20

--B. MUESTRA EL ID, CARNET, NOMBRE Y APELLIDOS DE LOS ESTUDIANTES QUE EN EL TOTAL DE LA MATRICULA TIENEN MAS DE 200000
SELECT ID_ESTUDIANTE, CARNET, NOMBRE, APELLIDO_01, APELLIDO_02
	FROM ESTUDIANTES
	WHERE ESTADO = 'ACT' AND --SI EL ESTADO DEL ESTUDIANTE ES ACTIVO
		(SELECT SUM (MONTOTOTAL) --ESTA CONSULTA SUMA LOS MONTOS TOTALES
			FROM MATERIAS_DISPONIBLES MD INNER JOIN MATRICULAS M
		
			ON MD.ID_MATERIA_ABIERTA = M.ID_MATERIA_ABIERTA
			INNER JOIN FACTURAS F
		
			ON M.ID_COMPROBANTE = F.ID_COMPROBANTE
		) > 200000 --MIENTRAS LA SUMA DE LOS MONTOS SEA MENOR A 200 000

----------------------------------------------------------------------------------------

--5. CONSULTAS DE CUALQUIER TIPO -------------------------------------------------------

--A.SUBCONSULTA: MUESTRA EL ID, CARNET Y NOMBRE DEL PROFESOR CON MATERIAS ASIGNADAS QUE TENGAN ENTRE 2 Y 12 FERIADOS Y QUE NO SEA VIERNES
SELECT DISTINCT E.ID_EMPLEADO, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO
	FROM EMPLEADOS E INNER JOIN PROFESORES P --LOS QUE ESTAN EN AMBAS TABLAS
	ON E.ID_EMPLEADO = P.ID_EMPLEADO

	INNER JOIN MATERIAS_DISPONIBLES MD
	ON P.ID_PROFESOR = MD.ID_PROFESOR
	
	WHERE EXISTS
		(SELECT COUNT(ID_FERIADO) --ESTA CONSULTA SUMA LA CANTIDAD DE DIAS FERIADOS QUE NO SEAN UN VIERNES
		FROM GRUPOS G INNER JOIN HORARIOS H
		
		ON G.ID_GRUPO = H.ID_GRUPO
		INNER JOIN FERIADOS F
		
		ON H.ID_HORARIO = F.ID_HORARIO
		WHERE DIA <> 'V'

		HAVING COUNT(ID_FERIADO) > 2 AND  COUNT(ID_FERIADO) < 12) --MIENTRAS LA CANTIDAD DE DIAS SEA MAYOR A 2 Y MENOR A 12

--B. MUESTRA ID, CARNET Y NOMBRE CONCATENADO DEL PROFESOR QUE CONTIENE UN CERTIFICADO CON EL NUM DE FOLIO MAS BAJO
SELECT P.ID_PROFESOR, CARNET,
	   NOMBRE + ' ' + APELLIDO_01 + ' ' + ' ' + APELLIDO_02 AS NOMBRE_COMPLETO
	FROM EMPLEADOS E INNER JOIN PROFESORES P --LOS QUE ESTAN EN AMBAS
	
	ON E.ID_EMPLEADO = P.ID_EMPLEADO
	INNER JOIN CERTIFICACIONES C

	ON P.ID_PROFESOR = C.ID_PROFESOR

	WHERE NUM_FOLIO = --ESTA CONSULTA BUSCA EL CERTIFICADO QUE PERTENEZCA AL NUMERO DE FOLIO MÁS PEQUEÑO
		(SELECT MIN(NUM_FOLIO) AS MATERIA_MENOR_COSTO
		FROM CERTIFICACIONES)
	



	   

		
		





